version: "3.8"
services:
  postgres_database:
    hostname: postgres_database
    container_name: postgres_database
    image: postgres:14.1
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "changeme"
      POSTGRES_USER: "postgres"
      PGPORT: 5432
    ports:
      - "5432:5432"
    networks:
      - service

networks:
  service: